### ISSUE TITLE
Query on collections doesn't work, method Collection(...) is not called

### ISSUE THREAD

**Issue by cgourdin** [erocci/erocci#66]
Hello Jean,

I still have a problem with collections on erocci / dbus java backend.
My query : 
`curl -v -X GET http://localhost:8080/categories/compute/`
I think there is a problem with dbus interface, i have already check erocci-dbus.xml and the interface on java dbus xml descriptor and there are the same, i dont understand why the number of argument is incorrect. It's maybe due to filter array (empty) ? 

How to query with curl and collections filters ?

I have this stack trace:
```
=INFO REPORT==== 27-Jun-2016::15:59:01 ===
[erocci_backend_dbus] collection(http://schemas.ogf.org/occi/infrastructure#compute)
=INFO REPORT==== 27-Jun-2016::15:59:01 ===
Calling <<"/">>:<<"org.ow2.erocci.backend.core">>.<<"Collection">>([<<"http://schemas.ogf.org/occi/infrastructure#compute">>,
                                                                    [],0,-1])

=INFO REPORT==== 27-Jun-2016::15:59:01 ===
<21> error: <<"Error Executing Method org.ow2.erocci.backend.core.Collection: wrong number of arguments">>

=INFO REPORT==== 27-Jun-2016::15:59:01 ===
Unknown exception from backend: <<"org.freedesktop.dbus.exceptions.DBusExecutionException">>
=INFO REPORT==== 27-Jun-2016::15:59:01 ===
Exception: <<"Error Executing Method org.ow2.erocci.backend.core.Collection: wrong number of arguments">>
=ERROR REPORT==== 27-Jun-2016::15:59:01 ===
HTTP listener error: <<"org.freedesktop.dbus.exceptions.DBusExecutionException">>

=INFO REPORT==== 27-Jun-2016::15:59:01 ===
ERROR (<<"*/*">>): <<"org.freedesktop.dbus.exceptions.DBusExecutionException">>
=ERROR REPORT==== 27-Jun-2016::15:59:01 ===
Ranch listener http had connection process started with cowboy_protocol:start_link/4 at <0.176.0> exit with reason: {badarg,[{erlang,iolist_size,[halt],[]},{cowboy_req,reply_may_compress,7,[{file,"src/cowboy_req.erl"},{line,762}]},{cowboy_req,reply,4,[{file,"src/cowboy_req.erl"},{line,749}]},{cowboy_rest,respond,3,[{file,"src/cowboy_rest.erl"},{line,1142}]},{cowboy_rest,set_resp_body,2,[{file,"src/cowboy_rest.erl"},{line,1018}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,470}]}]}

=ERROR REPORT==== 27-Jun-2016::15:59:01 ===
Error in process <0.176.0> on node 'node1@christophe-ubuntu' with exit value:
{badarg,[{erlang,iolist_size,[halt],[]},
         {cowboy_req,reply_may_compress,7,
                     [{file,"src/cowboy_req.erl"},{line,762}]},
         {cowboy_req,reply,4,[{file,"src/cowboy_req.erl"},{line,749}]},
         {cowboy_rest,respond,3,[{file,"src/cowboy_rest.erl"},{line,1142}]},
         {cowboy_rest,set_resp_body,2,
                      [{file,"src/cowboy_rest.erl"},{line,1018}]},
         {cowboy_protocol,execute,4,
                          [{file,"src/cowboy_protocol.erl"},{line,470}]}]}
```
Filter structure object (generated from xml descriptor) in List java:
```
import org.freedesktop.dbus.Position;
import org.freedesktop.dbus.Struct;
import org.freedesktop.dbus.Variant;
public final class Struct3 extends Struct
{
   @Position(0)
   public final byte a;
   @Position(1)
   public final String b;
   @Position(2)
   public final Variant c;
  public Struct3(byte a, String b, Variant c)
  {
   this.a = a;
   this.b = b;
   this.c = c;
  }
}
```
Thank you !

**Comment by jeanparpaillon** [comment]
Can you indicate how to run the backend with infrastructure extension and eventually any other information to reproduce it ?

**Comment by cgourdin** [comment]
You can run erocci dbus with class path need jars :
Note that you must replace paths by your path.

java -cp ./target/erocci-dbus-java-1.0-SNAPSHOT-jar-with-dependencies.jar:/home/christophe/.m2/repository/Clouddesigner/org.occiware.clouddesigner.occi.infrastructure/0.1.0-SNAPSHOT/org.occiware.clouddesigner.occi.infrastructure-0.1.0-SNAPSHOT.jar:/home/christophe/.m2/repository/Clouddesigner/org.occiware.clouddesigner.occi.infrastructure.connector.dummy/0.1.0-SNAPSHOT/org.occiware.clouddesigner.occi.infrastructure.connector.dummy-0.1.0-SNAPSHOT.jar org.ow2.erocci.backend.BackendDBusService

**Comment by jeanparpaillon** [comment]
Thanks !

**Comment by cgourdin** [comment]
for proceed if you dont have the cloud designers jar :
[jars.zip](https://github.com/erocci/erocci/files/338825/jars.zip)

**Comment by jeanparpaillon** [comment]
Backend seems to not recognize the jars:

```sh
java -cp ./target/erocci-dbus-java-1.0-SNAPSHOT-jar-with-dependencies.jar:~/.m2/repository/Clouddesigner/org.occiware.clouddesigner.occi.infrastructure/0.1.0-SNAPSHOT/org.occiware.clouddesigner.occi.infrastructure-0.1.0-SNAPSHOT.jar:~/.m2/repository/Clouddesigner/org.occiware.clouddesigner.occi.infrastructure.connector.dummy/0.1.0-SNAPSHOT/org.occiware.clouddesigner.occi.infrastructure.connector.dummy-0.1.0-SNAPSHOT.jar org.ow2.erocci.backend.BackendDBusService
INFO  BackendDBusService - Connected to dbus with unique name : :1.219
INFO  MART - OCCIware MART initializing...
INFO  MART -   Scanning all plugin.xml found in the classpath...
INFO  MART -     - EMF package org.occiware.clouddesigner.occi.OCCIPackage at http://schemas.ogf.org/occi/core/ecore registered.
INFO  MART -     - Ecore factory org.occiware.clouddesigner.occi.util.OCCIResourceFactoryImpl for file extension .occie registered.
INFO  MART -     - Ecore factory org.occiware.clouddesigner.occi.util.OCCIResourceFactoryImpl for file extension .occic registered.
INFO  MART -     - OCCI extension http://schemas.ogf.org/occi/core# contained in model/Core.occie registered.
INFO  MART - OCCIware MART initialized.
INFO  ConfigurationManager - Configuration for user anonymous created
INFO  ConfigurationManager - Collection: [http://schemas.ogf.org/occi/core#]
INFO  ConfigurationManager - Loading model extension : http://schemas.ogf.org/occi/core#
INFO  ConfigurationManager - Extension registered : http://schemas.ogf.org/occi/core#
INFO  ConfigurationManager - Add Erocci xml extension: core --< /erocci/core.xml
INFO  ConfigurationManager - FilePath : jar:file:/home/jean/BA_Projets/git/erocci-dbus-java/target/erocci-dbus-java-1.0-SNAPSHOT-jar-with-dependencies.jar!/erocci/core.xml
```

**Comment by cgourdin** [comment]
dont use ~ , replace by your full path.

**Comment by jeanparpaillon** [comment]
```sh 
java -cp ./target/erocci-dbus-java-1.0-SNAPSHOT-jar-with-dependencies.jar:$HOME/.m2/repository/Clouddesigner/org.occiware.clouddesigner.occi.infrastructure/0.1.0-SNAPSHOT/org.occiware.clouddesigner.occi.infrastructure-0.1.0-SNAPSHOT.jar:$HOME/.m2/repository/Clouddesigner/org.occiware.clouddesigner.occi.infrastructure.connector.dummy/0.1.0-SNAPSHOT/org.occiware.clouddesigner.occi.infrastructure.connector.dummy-0.1.0-SNAPSHOT.jar org.ow2.erocci.backend.BackendDBusService
INFO  BackendDBusService - Connected to dbus with unique name : :1.225
INFO  MART - OCCIware MART initializing...
INFO  MART -   Scanning all plugin.xml found in the classpath...
INFO  MART -     - EMF package org.occiware.clouddesigner.occi.OCCIPackage at http://schemas.ogf.org/occi/core/ecore registered.
INFO  MART -     - Ecore factory org.occiware.clouddesigner.occi.util.OCCIResourceFactoryImpl for file extension .occie registered.
INFO  MART -     - Ecore factory org.occiware.clouddesigner.occi.util.OCCIResourceFactoryImpl for file extension .occic registered.
INFO  MART -     - OCCI extension http://schemas.ogf.org/occi/core# contained in model/Core.occie registered.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.occiware.mart.MART.initMART(MART.java:120)
	at org.ow2.erocci.model.ConfigurationManager.<clinit>(ConfigurationManager.java:63)
	at org.ow2.erocci.backend.BackendDBusService.main(BackendDBusService.java:76)
Caused by: java.lang.NullPointerException
	at org.occiware.clouddesigner.occi.infrastructure.impl.InfrastructurePackageImpl.initializePackageContents(InfrastructurePackageImpl.java:836)
	at org.occiware.clouddesigner.occi.infrastructure.impl.InfrastructurePackageImpl.init(InfrastructurePackageImpl.java:247)
	at org.occiware.clouddesigner.occi.infrastructure.InfrastructurePackage.<clinit>(InfrastructurePackage.java:61)
	... 9 more
```

**Comment by cgourdin** [comment]
This problem is maybe cause by an old version of cloud designer package occi core. please update the referenced lib (i've updated dependency lib on github) with git pull and use dbus-java-install-script.sh before launch. To be sure to use the last infrastructure package use the jar i provided above, with unzip in a custom directory and update paths of the jars.

**Comment by jeanparpaillon** [comment]
Got it, removing ~/.m2 and starting from scratch.
Trying to reproduce now

**Comment by jeanparpaillon** [comment]
First conclusions:
* in the backend log, I see the following message:
```sh
INFO  CoreImpl - Create entity done returning relative path : http://schemas.ogf.org/occi/infrastructure#compute/78ad6bd8-aba0-48d8-85cf-c05a3bd88864
```

I don't know if the problem comes from here, but the location you return is not a relative path (as expected by erocci.

**Comment by jeanparpaillon** [comment]
Then, regarding the Collection function, it is fully described in the erocci-dbus.xml file:
```xml
<method name="Collection" >
      <xs:annotation>
        <xs:documentation>Retrieve a collection, eventually filtered</xs:documentation>
	<xs:documentation>
	  Filter is a list of constraint.
	  Constraint is a 3-tuple:
	  * operator: 0: EQUAL, 1: LIKE
	  * key (string): attribute on which apply the constraint (or empty string for any attribute)
	  * value (variant): constraint value
	</xs:documentation>
        <xs:documentation>
          In:
	  * id (string): category id or path
	  * filter (a(ysv)): filter
	  * start (unsigned integer): index of first record
	  * number (integer): maximal number of entities to retrieve, -1 for infinite
        </xs:documentation>
        <xs:documentation>
          Out:
	  * list of entities ('a(sasa{sv}sss)'):
	    * location (string): entity location
            * kind (string): kind id
	    * mixins (string array): mixin ids
	    * attributes (string/variant array): entity attributes
	    * links (string array): resource links locations
	    * owner (string): entity owner
	    * group (string): entity group owner
	  * serial (string): collection serial
        </xs:documentation>
      </xs:annotation>

      <arg name="id" type="s" direction="in" />
      <arg name="filter" type="a(ysv)" direction="in" />
      <arg name="start" type="u" direction="in" />
      <arg name="number" type="i" direction="in" />

      <arg name="entities" type="a(sasa{sv}sss)" direction="out" />
      <arg name="serial" type="s" direction="out" />
    </method>
```

**Comment by cgourdin** [comment]
Relative path when return entity :
`INFO  CoreImpl - Create entity done returning relative path : compute/cf8fab4b-5f36-439a-a85c-bc29ec97d37b`
This is what i have when i create the entity like this query : 
`curl -s -v -i -X PUT http://localhost:8080/compute/cf8fab4b-5f36-439a-a85c-bc29ec97d37b -H 'Content-Type: text/occi' -H 'Category: compute; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind";' -H 'X-OCCI-Attribute: occi.core.id="cf8fab4b-5f36-439a-a85c-bc29ec97d37b"' -H 'X-OCCI-Attribute: occi.core.title="Occiware Tuto2"' -H 'X-OCCI-Attribute: occi.core.summary="Occiware Tutorial Presentation"' -H 'X-OCCI-Attribute: occi.compute.architecture="x64"' -H 'X-OCCI-Attribute: occi.compute.cores=2' -H 'X-OCCI-Attribute: occi.compute.hostname="nohostname"' -H 'X-OCCI-Attribute: occi.compute.share=0' -H 'X-OCCI-Attribute: occi.compute.speed=0.0' -H 'X-OCCI-Attribute: occi.compute.memory=4.0' -H 'X-OCCI-Attribute: occi.compute.state="inactive"' -H 'X-OCCI-Attribute: occi.compute.state.message="No messages"'`

**Comment by jeanparpaillon** [comment]
Hum, sorry I forgot to mention the request who leads to this error... and forgot it :/
I suspect the error coming from the return value of your Collection function. Can you ensure it is:
* a list
* a string

The list being made of the following elements:
* location (string)
* kind (string)
* mixins (string)
* attributes (string/variant array)
* links (string array)
* owner (string)
* group (string)

**Comment by cgourdin** [comment]
On output the xml declared from erocci-dbus.xml is : 
```
<arg name="entities" type="a(sasa{sv}sss)" direction="out" />
<arg name="serial" type="s" direction="out" />
```
The generated objects from this xml on output : 

Pair object:
```
package org.ow2.erocci.backend;
import org.freedesktop.dbus.Position;
import org.freedesktop.dbus.Tuple;
/** Just a typed container class */
public final class Pair <A,B> extends Tuple
{
   @Position(0)
   public final A a;
   @Position(1)
   public final B b;
   public Pair(A a, B b)
   {
      this.a = a;
      this.b = b;
   }
}
```
Where this pair object contain :
a = List<Struct2>
b = String serial value.
A struct2 is defined as this : 
```
package org.ow2.erocci.backend;
import java.util.List;
import java.util.Map;
import org.freedesktop.dbus.Position;
import org.freedesktop.dbus.Struct;
import org.freedesktop.dbus.Variant;
public final class Struct2 extends Struct
{
   @Position(0)
   public final String a;
   @Position(1)
   public final List<String> b;
   @Position(2)
   public final Map<String,Variant> c;
   @Position(3)
   public final String d;
   @Position(4)
   public final String e;
   @Position(5)
   public final String f;
  public Struct2(String a, List<String> b, Map<String,Variant> c, String d, String e, String f)
  {
   this.a = a;
   this.b = b;
   this.c = c;
   this.d = d;
   this.e = e;
   this.f = f;
  }
}
```
Where values of struct2 : 
struct2 = new Struct2(location, mixins, attributes, kind, owner, group);
a = location
b = mixins
c = attributes
d = kind 
e = owner
f = group
**The kind value is maybe misplaced but to render the output, the b value is a List of String, not a String value.**,  I think there is a problem with output signature on xml because my generated object has not the same signature as the specification given from your xml and mine, **kind** may be in second position not the fourth position.

**Comment by jeanparpaillon** [comment]
fyi, I'm running backend with debug enable on dbus-java, which allows me to see that Collection method get 3 arguments while erocci is sending 4... Now investigating why...
To enable debug on dbus-java, rebuild with env var DEBUG=enable then run with env var DBUS_JAVA_EXCEPTION_DEBUG=true

**Comment by cgourdin** [comment]
Thanks for this information, this is really helpful !

**Comment by jeanparpaillon** [comment]
D-Bus API upgraded: Collection returns a list of url, not entity description.

See https://github.com/erocci/erocci_backend_dbus/blob/master/priv/erocci-dbus.xml#L301

**Comment by jeanparpaillon** [comment]
Fixed with https://github.com/occiware/erocci-dbus-java/commit/584b73d1874f82ea8810df2a66151f55ee6deee6
